/**
 * Project Template Definitions
 * All pre-made templates for Link's code generation
 */

// ==================== NEXT.JS 15 TEMPLATE ====================
export const NEXTJS_TEMPLATE = {
  id: 'nextjs-app-router',
  name: 'Next.js 15 App Router',
  category: 'Frontend',
  description: 'Modern Next.js 15 with TypeScript, App Router, and Tailwind CSS',
  files: {
    'package.json': `{
  "name": "my-nextjs-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.5.9",
    "react": "^19.2.1",
    "react-dom": "^19.2.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "typescript": "^5",
    "tailwindcss": "^3.4.1",
    "postcss": "^8",
    "autoprefixer": "^10"
  }
}`,

    'tsconfig.json': `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,

    'next.config.ts': `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {};

export default nextConfig;`,

    'tailwind.config.ts': `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: { extend: {} },
  plugins: [],
}
export default config`,

    'postcss.config.mjs': `const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;`,

    'src/app/layout.tsx': `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by Link',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,

    'src/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js 15</h1>
      <p className="mt-4 text-lg text-gray-600">Generated by Link</p>
    </main>
  )
}`,

    'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;`,

    '.gitignore': `node_modules
.next
out
build
.DS_Store
*.pem
npm-debug.log*
.env*.local
.vercel
*.tsbuildinfo
next-env.d.ts`,

    'README.md': `# My Next.js App

Generated by Link - ADK Link

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000)
`
  }
};

// ==================== EXPRESS API TEMPLATE ====================
export const EXPRESS_TEMPLATE = {
  id: 'express-api',
  name: 'Express REST API',
  category: 'Backend',
  description: 'Express.js API with TypeScript and basic CRUD structure',
  files: {
    'package.json': `{
  "name": "my-express-api",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  },
  "dependencies": {
    "express": "^4.21.2",
    "cors": "^2.8.5",
    "dotenv": "^16.5.0"
  },
  "devDependencies": {
    "@types/express": "^5.0.0",
    "@types/cors": "^2.8.17",
    "@types/node": "^20",
    "typescript": "^5",
    "tsx": "^4.19.2"
  }
}`,

    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "lib": ["ES2022"],
    "moduleResolution": "node",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}`,

    'src/index.ts': `import express, { Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Routes
app.get('/', (req: Request, res: Response) => {
  res.json({ message: 'API is running', generatedBy: 'Link' });
});

app.get('/api/health', (req: Request, res: Response) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

// Start server
app.listen(PORT, () => {
  console.log(\`🚀 Server running on http://localhost:\${PORT}\`);
});`,

    '.env.example': `PORT=3000
NODE_ENV=development`,

    '.gitignore': `node_modules
dist
.env
*.log`,

    'README.md': `# Express API

Generated by Link - ADK Link

## Getting Started

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`

API runs on http://localhost:3000
`
  }
};

// ==================== PYTHON CLI TEMPLATE ====================
export const PYTHON_CLI_TEMPLATE = {
  id: 'python-cli',
  name: 'Python CLI Tool',
  category: 'Backend',
  description: 'Python command-line tool with argparse',
  files: {
    'main.py': `#!/usr/bin/env python3
"""
Main CLI application
Generated by Link - ADK Link
"""

import argparse
import sys

def main():
    parser = argparse.ArgumentParser(
        description='My CLI Tool - Generated by Link'
    )
    parser.add_argument(
        'command',
        choices=['hello', 'version'],
        help='Command to execute'
    )
    parser.add_argument(
        '--name',
        default='World',
        help='Name to greet (for hello command)'
    )
    
    args = parser.parse_args()
    
    if args.command == 'hello':
        print(f"Hello, {args.name}!")
    elif args.command == 'version':
        print("Version 1.0.0 - Generated by Link")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())`,

    'requirements.txt': `# Add your dependencies here
`,

    '.gitignore': `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
ENV/
.venv
*.egg-info/
dist/
build/`,

    'README.md': `# Python CLI Tool

Generated by Link - ADK Link

## Setup

\`\`\`bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
\`\`\`

## Usage

\`\`\`bash
python main.py hello --name "Link"
python main.py version
\`\`\`
`
  }
};

// ==================== RUST CLI TEMPLATE ====================
export const RUST_CLI_TEMPLATE = {
  id: 'rust-cli',
  name: 'Rust CLI Tool',
  category: 'Backend',
  description: 'Rust CLI with clap for argument parsing',
  files: {
    'Cargo.toml': `[package]
name = "my-cli-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }`,

    'src/main.rs': `use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "my-cli")]
#[command(about = "Generated by Link - ADK Link", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Say hello
    Hello {
        /// Name to greet
        #[arg(short, long, default_value = "World")]
        name: String,
    },
    /// Show version
    Version,
}

fn main() {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Hello { name } => {
            println!("Hello, {}!", name);
        }
        Commands::Version => {
            println!("Version 0.1.0 - Generated by Link");
        }
    }
}`,

    '.gitignore': `/target/
**/*.rs.bk
Cargo.lock`,

    'README.md': `# Rust CLI Tool

Generated by Link - ADK Link

## Build & Run

\`\`\`bash
cargo build
cargo run -- hello --name Link
cargo run -- version
\`\`\`

## Install

\`\`\`bash
cargo install --path .
\`\`\`
`
  }
};

// ==================== GO CLI TEMPLATE ====================
export const GO_CLI_TEMPLATE = {
  id: 'go-cli',
  name: 'Go CLI Tool',
  category: 'Backend',
  description: 'Go command-line application with Cobra framework',
  files: {
    'go.mod': `module mycli

go 1.21

require github.com/spf13/cobra v1.8.0`,

    'main.go': `package main

import (
\t"fmt"
\t"os"
\t
\t"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
\tUse:   "mycli",
\tShort: "A CLI tool built with Go",
\tLong:  "A command-line tool built with Go and Cobra framework",
\tRun: func(cmd *cobra.Command, args []string) {
\t\tfmt.Println("Hello from Go CLI!")
\t},
}

func main() {
\tif err := rootCmd.Execute(); err != nil {
\t\tfmt.Println(err)
\t\tos.Exit(1)
\t}
}`,

    'README.md': `# Go CLI Tool

A command-line application built with Go and Cobra.

## Installation

\`\`\`bash
go mod download
go build -o mycli
\`\`\`

## Usage

\`\`\`bash
./mycli
\`\`\``,

    '.gitignore': `# Binaries
mycli
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output
*.out

# Go workspace
go.work`
  }
};

// ==================== FASTAPI TEMPLATE ====================
export const FASTAPI_TEMPLATE = {
  id: 'fastapi',
  name: 'FastAPI',
  category: 'Backend',
  description: 'Modern Python API with FastAPI, async support, and auto docs',
  files: {
    'main.py': `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="My FastAPI",
    description="A modern Python API",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "Hello from FastAPI!"}

@app.get("/health")
async def health():
    return {"status": "healthy"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`,

    'requirements.txt': `fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.5.3`,

    'README.md': `# FastAPI Application

A modern Python API built with FastAPI.

## Installation

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Run

\`\`\`bash
python main.py
\`\`\`

Visit http://localhost:8000/docs for interactive API documentation.`,

    '.gitignore': `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.env
.venv/`
  }
};

// ==================== NESTJS TEMPLATE ====================
export const NESTJS_TEMPLATE = {
  id: 'nestjs',
  name: 'NestJS',
  category: 'Backend',
  description: 'Enterprise TypeScript framework with dependency injection',
  files: {
    'package.json': `{
  "name": "my-nestjs-api",
  "version": "0.0.1",
  "scripts": {
    "start": "nest start",
    "start:dev": "nest start --watch",
    "build": "nest build"
  },
  "dependencies": {
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^10.0.0",
    "@types/node": "^20.3.1",
    "typescript": "^5.1.3"
  }
}`,

    'src/main.ts': `import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  await app.listen(3000);
  console.log('NestJS running on http://localhost:3000');
}
bootstrap();`,

    'src/app.module.ts': `import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}`,

    'src/app.controller.ts': `import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}`,

    'src/app.service.ts': `import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'Hello from NestJS!';
  }
}`,

    'tsconfig.json': `{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}`,

    'README.md': `# NestJS API

Enterprise-grade TypeScript API framework.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run start:dev
\`\`\``,

    '.gitignore': `node_modules/
dist/
.env`
  }
};

// ==================== DJANGO TEMPLATE ====================
export const DJANGO_TEMPLATE = {
  id: 'django',
  name: 'Django',
  category: 'Backend',
  description: 'Full-featured Python web framework with ORM and admin',
  files: {
    'manage.py': `#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed?"
        ) from exc
    execute_from_command_line(sys.argv)`,

    'myproject/settings.py': `from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-change-this-in-production'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STATIC_URL = 'static/'`,

    'myproject/urls.py': `from django.contrib import admin
from django.urls import path
from django.http import JsonResponse

def home(request):
    return JsonResponse({"message": "Hello from Django!"})

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
]`,

    'myproject/__init__.py': '',

    'requirements.txt': `Django==5.0.1`,

    'README.md': `# Django Project

Full-featured Python web framework.

## Installation

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Run

\`\`\`bash
python manage.py migrate
python manage.py runserver
\`\`\``,

    '.gitignore': `*.pyc
__pycache__/
db.sqlite3
.env
venv/`
  }
};

// ==================== FLUTTER TEMPLATE ====================
export const FLUTTER_TEMPLATE = {
  id: 'flutter',
  name: 'Flutter',
  category: 'Mobile',
  description: 'Cross-platform mobile app with Dart and Flutter',
  files: {
    'pubspec.yaml': `name: my_flutter_app
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true`,

    'lib/main.dart': `import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}`,

    'README.md': `# Flutter App

Cross-platform mobile application.

## Installation

\`\`\`bash
flutter pub get
\`\`\`

## Run

\`\`\`bash
flutter run
\`\`\``,

    '.gitignore': `.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.packages
build/
.ios/
.android/`
  }
};

// ==================== REACT NATIVE TEMPLATE ====================
export const REACT_NATIVE_TEMPLATE = {
  id: 'react-native',
  name: 'React Native',
  category: 'Mobile',
  description: 'Cross-platform mobile app with React Native and Expo',
  files: {
    'package.json': `{
  "name": "my-react-native-app",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.2",
    "expo": "~50.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  }
}`,

    'App.tsx': `import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Hello React Native!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
});`,

    'app.json': `{
  "expo": {
    "name": "my-react-native-app",
    "slug": "my-react-native-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    }
  }
}`,

    'tsconfig.json': `{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true
  }
}`,

    'README.md': `# React Native App

Cross-platform mobile app with Expo.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm start
\`\`\`

Scan QR code with Expo Go app.`,

    '.gitignore': `node_modules/
.expo/
dist/
npm-debug.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/`
  }
};

// ==================== ANDROID KOTLIN TEMPLATE ====================
export const ANDROID_KOTLIN_TEMPLATE = {
  id: 'android-kotlin',
  name: 'Android (Kotlin)',
  category: 'Mobile',
  description: 'Native Android app with Kotlin and Jetpack Compose',
  files: {
    'build.gradle': `plugins {
    id 'com.android.application' version '8.2.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
}`,

    'app/build.gradle': `plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.myapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.myapp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.1'
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.2'
    implementation 'androidx.activity:activity-compose:1.8.2'
    implementation platform('androidx.compose:compose-bom:2023.08.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3'
}`,

    'app/src/main/AndroidManifest.xml': `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="My App"
        android:theme="@style/Theme.AppCompat">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`,

    'app/src/main/java/com/example/myapp/MainActivity.kt': `package com.example.myapp

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(modifier = Modifier.fillMaxSize()) {
                    Greeting("Android")
                }
            }
        }
    }
}

@Composable
fun Greeting(name: String) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(text = "Hello $name!")
    }
}`,

    'settings.gradle': `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "My App"
include ':app'`,

    'README.md': `# Android Kotlin App

Native Android app with Jetpack Compose.

## Build

\`\`\`bash
./gradlew build
\`\`\`

## Run

Open in Android Studio and run on emulator or device.`,

    '.gitignore': `.gradle/
build/
.idea/
*.iml
local.properties`
  }
};

// ==================== REACT VITE TEMPLATE ====================
export const REACT_VITE_TEMPLATE = {
  id: 'react-vite',
  name: 'React + Vite',
  category: 'Frontend',
  description: 'Modern React with Vite, TypeScript, and fast HMR',
  files: {
    'package.json': `{
  "name": "my-react-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.43",
    "@types/react-dom": "^18.2.17",
    "@vitejs/plugin-react": "^4.2.1",
    "typescript": "^5.2.2",
    "vite": "^5.0.8"
  }
}`,

    'vite.config.ts': `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`,

    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}`,

    'tsconfig.node.json': `{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}`,

    'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React + Vite</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,

    'src/main.tsx': `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,

    'src/App.tsx': `import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <h1>React + Vite</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
    </div>
  )
}

export default App`,

    'src/App.css': `.App {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.card {
  padding: 2em;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}`,

    'src/index.css': `body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}`,

    'README.md': `# React + Vite

Modern React application with Vite and TypeScript.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run dev
\`\`\`

Visit http://localhost:5173`,

    '.gitignore': `node_modules
dist
.env`
  }
};

// ==================== VUE TEMPLATE ====================
export const VUE_TEMPLATE = {
  id: 'vue-vite',
  name: 'Vue 3 + Vite',
  category: 'Frontend',
  description: 'Vue 3 with Composition API, TypeScript, and Vite',
  files: {
    'package.json': `{
  "name": "my-vue-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.4.15"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.3",
    "typescript": "^5.2.2",
    "vite": "^5.0.8",
    "vue-tsc": "^1.8.27"
  }
}`,

    'vite.config.ts': `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
})`,

    'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
  "references": [{ "path": "./tsconfig.node.json" }]
}`,

    'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue 3 + Vite</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>`,

    'src/main.ts': `import { createApp } from 'vue'
import './style.css'
import App from './App.vue'

createApp(App).mount('#app')`,

    'src/App.vue': `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div>
    <h1>Vue 3 + Vite</h1>
    <div class="card">
      <button type="button" @click="count++">count is {{ count }}</button>
    </div>
  </div>
</template>

<style scoped>
.card {
  padding: 2em;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}
</style>`,

    'src/style.css': `body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}`,

    'README.md': `# Vue 3 + Vite

Vue 3 application with Composition API and TypeScript.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run dev
\`\`\`

Visit http://localhost:5173`,

    '.gitignore': `node_modules
dist
.env`
  }
};

// ==================== SVELTE TEMPLATE ====================
export const SVELTE_TEMPLATE = {
  id: 'svelte-vite',
  name: 'Svelte + Vite',
  category: 'Frontend',
  description: 'Lightweight Svelte with TypeScript and Vite',
  files: {
    'package.json': `{
  "name": "my-svelte-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-check --tsconfig ./tsconfig.json"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^3.0.1",
    "svelte": "^4.2.8",
    "svelte-check": "^3.6.2",
    "tslib": "^2.6.2",
    "typescript": "^5.2.2",
    "vite": "^5.0.8"
  }
}`,

    'vite.config.ts': `import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

export default defineConfig({
  plugins: [svelte()],
})`,

    'tsconfig.json': `{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "resolveJsonModule": true,
    "allowJs": true,
    "checkJs": true,
    "isolatedModules": true
  },
  "include": ["src/**/*.d.ts", "src/**/*.ts", "src/**/*.js", "src/**/*.svelte"],
  "references": [{ "path": "./tsconfig.node.json" }]
}`,

    'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Svelte + Vite</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>`,

    'src/main.ts': `import './app.css'
import App from './App.svelte'

const app = new App({
  target: document.getElementById('app')!,
})

export default app`,

    'src/App.svelte': `<script lang="ts">
  let count: number = 0
  const increment = () => {
    count += 1
  }
</script>

<main>
  <h1>Svelte + Vite</h1>
  <div class="card">
    <button on:click={increment}>
      count is {count}
    </button>
  </div>
</main>

<style>
  .card {
    padding: 2em;
  }

  button {
    border-radius: 8px;
    border: 1px solid transparent;
    padding: 0.6em 1.2em;
    font-size: 1em;
    font-weight: 500;
    background-color: #1a1a1a;
    cursor: pointer;
    transition: border-color 0.25s;
  }

  button:hover {
    border-color: #646cff;
  }
</style>`,

    'src/app.css': `body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}`,

    'README.md': `# Svelte + Vite

Lightweight Svelte application with TypeScript.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run dev
\`\`\`

Visit http://localhost:5173`,

    '.gitignore': `node_modules
dist
.env`
  }
};

// ==================== HTML + TAILWIND TEMPLATE ====================
export const HTML_TAILWIND_TEMPLATE = {
  id: 'html-tailwind',
  name: 'HTML + Tailwind CSS',
  category: 'Frontend',
  description: 'Pure HTML with Tailwind CSS and Vite for modern styling',
  files: {
    'package.json': `{
  "name": "my-html-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.32",
    "tailwindcss": "^3.4.0",
    "vite": "^5.0.8"
  }
}`,

    'vite.config.js': `import { defineConfig } from 'vite'

export default defineConfig({
  // No special config needed for vanilla HTML
})`,

    'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`,

    'postcss.config.js': `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,

    'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HTML + Tailwind CSS</title>
    <link rel="stylesheet" href="/src/style.css">
  </head>
  <body class="bg-gray-900 text-white">
    <div id="app" class="min-h-screen flex items-center justify-center">
      <div class="text-center space-y-8">
        <h1 class="text-5xl font-bold bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent">
          HTML + Tailwind CSS
        </h1>
        <div class="card p-8 bg-gray-800 rounded-lg shadow-xl">
          <button 
            id="counterBtn"
            class="px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-semibold transition-colors"
          >
            Count is <span id="count">0</span>
          </button>
        </div>
      </div>
    </div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>`,

    'src/main.js': `let count = 0

document.getElementById('counterBtn').addEventListener('click', () => {
  count++
  document.getElementById('count').textContent = count
})

console.log('HTML + Tailwind CSS app ready!')`,

    'src/style.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
}`,

    'README.md': `# HTML + Tailwind CSS

Pure HTML web app with Tailwind CSS for modern styling.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run dev
\`\`\`

Visit http://localhost:5173

## Features

- 🎨 Tailwind CSS for utility-first styling
- ⚡ Vite for fast development
- 📦 Zero JavaScript framework overhead
- 🚀 Perfect for landing pages, portfolios, simple web apps`,

    '.gitignore': `node_modules
dist
.env`
  }
};

// ==================== ASTRO TEMPLATE ====================
export const ASTRO_TEMPLATE = {
  id: 'astro',
  name: 'Astro',
  category: 'Frontend',
  description: 'Modern static site generator with islands architecture',
  files: {
    'package.json': `{
  "name": "my-astro-app",
  "type": "module",
  "version": "0.1.0",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview"
  },
  "dependencies": {
    "astro": "^4.1.1"
  }
}`,

    'astro.config.mjs': `import { defineConfig } from 'astro/config';

export default defineConfig({});`,

    'tsconfig.json': `{
  "extends": "astro/tsconfigs/base"
}`,

    'src/pages/index.astro': `---
const pageTitle = "Astro App";
let count = 0;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{pageTitle}</title>
  </head>
  <body>
    <main>
      <h1>Welcome to Astro</h1>
      <p>Build faster websites with less client-side JavaScript.</p>
      <button id="counter">Count is {count}</button>
    </main>
  </body>
</html>

<style>
  body {
    margin: 0;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: system-ui, sans-serif;
    background: #13151a;
    color: white;
  }

  main {
    text-align: center;
  }

  h1 {
    font-size: 3rem;
    background: linear-gradient(45deg, #4f46e5, #7c3aed);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  button {
    padding: 1rem 2rem;
    background: #4f46e5;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-size: 1rem;
    cursor: pointer;
    transition: all 0.2s;
  }

  button:hover {
    background: #4338ca;
  }
</style>

<script>
  let count = 0;
  const btn = document.getElementById('counter');
  btn?.addEventListener('click', () => {
    count++;
    if (btn) btn.textContent = \`Count is \${count}\`;
  });
</script>`,

    'README.md': `# Astro App

Modern static site generator with islands architecture.

## Installation

\`\`\`bash
npm install
\`\`\`

## Run

\`\`\`bash
npm run dev
\`\`\`

Visit http://localhost:4321

## Features

- 🏝️ Islands architecture
- ⚡ Zero JS by default
- 🚀 Fast page loads
- 📦 Framework agnostic`,

    '.gitignore': `node_modules
dist
.env`
  }
};

// ==================== TEMPLATE REGISTRY ====================
export interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  files: Record<string, string>;
}

export const ALL_TEMPLATES: Template[] = [
  // Frontend
  NEXTJS_TEMPLATE,
  REACT_VITE_TEMPLATE,
  VUE_TEMPLATE,
  SVELTE_TEMPLATE,
  HTML_TAILWIND_TEMPLATE,
  ASTRO_TEMPLATE,
  
  // Backend
  EXPRESS_TEMPLATE,
  PYTHON_CLI_TEMPLATE,
  RUST_CLI_TEMPLATE,
  GO_CLI_TEMPLATE,
  FASTAPI_TEMPLATE,
  NESTJS_TEMPLATE,
  DJANGO_TEMPLATE,
  
  // Mobile
  FLUTTER_TEMPLATE,
  REACT_NATIVE_TEMPLATE,
  ANDROID_KOTLIN_TEMPLATE,
];

/**
 * Detect which template to use based on user prompt
 */
export function detectTemplate(userPrompt: string): Template | null {
  const lower = userPrompt.toLowerCase();
  
  // Next.js detection
  if (lower.includes('nextjs') || lower.includes('next.js') || lower.includes('next app')) {
    return NEXTJS_TEMPLATE;
  }
  
  // Express API detection
  if ((lower.includes('express') || lower.includes('rest api') || lower.includes('api server')) 
      && (lower.includes('node') || lower.includes('typescript'))) {
    return EXPRESS_TEMPLATE;
  }
  
  // Python CLI detection
  if (lower.includes('python') && (lower.includes('cli') || lower.includes('command line') || lower.includes('tool'))) {
    return PYTHON_CLI_TEMPLATE;
  }
  
  // Rust CLI detection
  if (lower.includes('rust') && (lower.includes('cli') || lower.includes('command line') || lower.includes('tool'))) {
    return RUST_CLI_TEMPLATE;
  }
  
  return null;
}

/**
 * Get template by ID
 */
export function getTemplateById(id: string): Template | undefined {
  return ALL_TEMPLATES.find(t => t.id === id);
}

/**
 * Find templates matching a query
 */
export function findTemplates(query: string): Template[] {
  const lowerQuery = query.toLowerCase();
  return ALL_TEMPLATES.filter(t => 
    t.name.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery)
  );
}
